services:
  minio:
    image: quay.io/minio/minio
    container_name: minio_object_storage1
    env_file:
      - .env
    volumes:
      - D:\minio\data:/data
    command: server /data --console-address ":9001"
    ports:
      - "9000:9000"
      - "9001:9001"
    networks:
        - minio-network

  minio-service:
    image: my-minio-app
    container_name: minio_service
    build:
      context: .
      dockerfile: Dockerfile
    ports:
        - "8080:8080"
    env_file:
        - .env
    depends_on:
      - minio
    networks:
        - minio-network

networks:
    minio-network:
        driver: bridge